create database COMPANY
USE COMPANY

CREATE TABLE EMPLOYEE (ID INT PRIMARY KEY IDENTITY (1,1), NAME VARCHAR(250), SALARY BIGINT)
INSERT INTO EMPLOYEE(NAME,SALARY) VALUES
('Bari',8000),
('Habeeb',12000),
('Anwar',80000),
('Ameen',200000);
select * from EMPLOYEE

