CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(STUDENT_ID INT PRIMARY KEY,NAME VARCHAR(250),AGE INT)
INSERT INTO STUDENT(STUDENT_ID,NAME,AGE)VALUES
(1,'PRAN',24);
INSERT INTO STUDENT(STUDENT_ID,NAME,AGE)VALUES
(2,'HABEEB',24),
(3,'AMEEN',22),
(4,'ANWAR',34);
SELECT * FROM STUDENT

CREATE PROCEDURE GETDETAILES @ID INT
AS
BEGIN
SELECT * FROM STUDENT WHERE @ID =STUDENT_ID
END

EXEC GETDETAILES 2              